ersion: '3.8'

services: 
    postgres: 
        image: postgres
        networks: 
            - calendso_network
        env_file: .env
        restart: 'always'
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./init-user-db/postgresql/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
    # mysql: 
    #     image: mysql
    #     command: --default-authentication-plugin=mysql_native_password
    #     networks: 
    #         - calendso_network
    #     env_file: .env
    #     restart: 'always'
    #     ports:
    #         - 3306:3306
    #     volumes:
    #         - mysql_data:/var/lib/mysql
    #         - ./init-user-db/mysql/init-user-db.sql:/docker-entrypoint-initdb.d/init-user-db.sql:ro
    smtp:
        image: mailhog/mailhog
        ports:
            - 1025:1025
            - 8025:8025
    calendso:
        build: .
        networks: 
            - calendso_network
        volumes: 
            - .:/buildpack
            - cache:/cache
            - build:/build
            - env:/env
            - app:/app
        env_file: .env
        ports: 
            - 8065:8065
        depends_on:
            - postgres
            # - mysql
volumes: 
    postgres_data:
    mysql_data:
    cache:
    build:
    env:
    app:
networks: 
    calendso_network:
